// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	GetUserByName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*User, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) GetUserByName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.OrchestratorService/GetUserByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility
type OrchestratorServiceServer interface {
	GetUserByName(context.Context, *UserName) (*User, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServiceServer struct {
}

func (UnimplementedOrchestratorServiceServer) GetUserByName(context.Context, *UserName) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByName not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_GetUserByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetUserByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.OrchestratorService/GetUserByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetUserByName(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByName",
			Handler:    _OrchestratorService_GetUserByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}

// MockDataServiceClient is the client API for MockDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockDataServiceClient interface {
	GetMockUserData(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*User, error)
}

type mockDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockDataServiceClient(cc grpc.ClientConnInterface) MockDataServiceClient {
	return &mockDataServiceClient{cc}
}

func (c *mockDataServiceClient) GetMockUserData(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.MockDataService/GetMockUserData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockDataServiceServer is the server API for MockDataService service.
// All implementations must embed UnimplementedMockDataServiceServer
// for forward compatibility
type MockDataServiceServer interface {
	GetMockUserData(context.Context, *UserName) (*User, error)
	mustEmbedUnimplementedMockDataServiceServer()
}

// UnimplementedMockDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMockDataServiceServer struct {
}

func (UnimplementedMockDataServiceServer) GetMockUserData(context.Context, *UserName) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMockUserData not implemented")
}
func (UnimplementedMockDataServiceServer) mustEmbedUnimplementedMockDataServiceServer() {}

// UnsafeMockDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockDataServiceServer will
// result in compilation errors.
type UnsafeMockDataServiceServer interface {
	mustEmbedUnimplementedMockDataServiceServer()
}

func RegisterMockDataServiceServer(s grpc.ServiceRegistrar, srv MockDataServiceServer) {
	s.RegisterService(&MockDataService_ServiceDesc, srv)
}

func _MockDataService_GetMockUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDataServiceServer).GetMockUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.MockDataService/GetMockUserData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDataServiceServer).GetMockUserData(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

// MockDataService_ServiceDesc is the grpc.ServiceDesc for MockDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.MockDataService",
	HandlerType: (*MockDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMockUserData",
			Handler:    _MockDataService_GetMockUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}

// Orchestrator2ServiceClient is the client API for Orchestrator2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Orchestrator2ServiceClient interface {
	GetUser(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*User, error)
}

type orchestrator2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrator2ServiceClient(cc grpc.ClientConnInterface) Orchestrator2ServiceClient {
	return &orchestrator2ServiceClient{cc}
}

func (c *orchestrator2ServiceClient) GetUser(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.Orchestrator2Service/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Orchestrator2ServiceServer is the server API for Orchestrator2Service service.
// All implementations must embed UnimplementedOrchestrator2ServiceServer
// for forward compatibility
type Orchestrator2ServiceServer interface {
	GetUser(context.Context, *UserName) (*User, error)
	mustEmbedUnimplementedOrchestrator2ServiceServer()
}

// UnimplementedOrchestrator2ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestrator2ServiceServer struct {
}

func (UnimplementedOrchestrator2ServiceServer) GetUser(context.Context, *UserName) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedOrchestrator2ServiceServer) mustEmbedUnimplementedOrchestrator2ServiceServer() {}

// UnsafeOrchestrator2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Orchestrator2ServiceServer will
// result in compilation errors.
type UnsafeOrchestrator2ServiceServer interface {
	mustEmbedUnimplementedOrchestrator2ServiceServer()
}

func RegisterOrchestrator2ServiceServer(s grpc.ServiceRegistrar, srv Orchestrator2ServiceServer) {
	s.RegisterService(&Orchestrator2Service_ServiceDesc, srv)
}

func _Orchestrator2Service_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Orchestrator2ServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Orchestrator2Service/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Orchestrator2ServiceServer).GetUser(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator2Service_ServiceDesc is the grpc.ServiceDesc for Orchestrator2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Orchestrator2Service",
	HandlerType: (*Orchestrator2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Orchestrator2Service_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
